/**
 * Alert Domain Specification
 *
 * Defines alerts generated by the Protect engine for fraud detection
 * and anomaly identification.
 */

import { z } from 'zod';
import { RiskFlagSchema } from './transaction.spec';

// =============================================================================
// ENUMS
// =============================================================================

export const AlertTypeSchema = z.enum([
  'fraud',           // Suspected fraudulent activity
  'anomaly',         // Unusual pattern detected
  'threshold',       // Spending threshold exceeded
  'security',        // Security concern (login, device, etc.)
  'compliance',      // Regulatory compliance issue
]);
export type AlertType = z.infer<typeof AlertTypeSchema>;

export const AlertSeveritySchema = z.enum(['low', 'medium', 'high', 'critical']);
export type AlertSeverity = z.infer<typeof AlertSeveritySchema>;

export const AlertStatusSchema = z.enum(['active', 'investigating', 'dismissed', 'resolved', 'escalated']);
export type AlertStatus = z.infer<typeof AlertStatusSchema>;

// =============================================================================
// MAIN SCHEMA
// =============================================================================

export const AlertSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),

  // Alert Classification
  type: AlertTypeSchema,
  severity: AlertSeveritySchema,
  status: AlertStatusSchema,

  // Content
  title: z.string().max(200),
  message: z.string().max(1000),
  details: z.record(z.unknown()).optional(), // Flexible metadata

  // Risk Analysis
  riskScore: z.number().min(0).max(100),
  confidence: z.number().min(0).max(100), // Model confidence
  riskFlag: RiskFlagSchema,

  // Relationships
  transactionId: z.string().uuid().nullable().optional(),
  relatedAlertIds: z.array(z.string().uuid()).default([]),

  // Resolution
  dismissedAt: z.string().datetime().nullable().optional(),
  dismissedBy: z.string().uuid().nullable().optional(),
  dismissReason: z.string().max(500).nullable().optional(),
  resolvedAt: z.string().datetime().nullable().optional(),
  resolution: z.string().max(1000).nullable().optional(),

  // Timestamps
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  expiresAt: z.string().datetime().nullable().optional(),
});

export type Alert = z.infer<typeof AlertSchema>;

// =============================================================================
// ACTION SCHEMAS
// =============================================================================

export const DismissAlertSchema = z.object({
  alertId: z.string().uuid(),
  reason: z.string().min(1).max(500),
  dismissedBy: z.string().uuid(),
});

export type DismissAlert = z.infer<typeof DismissAlertSchema>;

export const ResolveAlertSchema = z.object({
  alertId: z.string().uuid(),
  resolution: z.string().min(1).max(1000),
  resolvedBy: z.string().uuid(),
});

export type ResolveAlert = z.infer<typeof ResolveAlertSchema>;

// =============================================================================
// FILTER & AGGREGATION
// =============================================================================

export const AlertFilterSchema = z.object({
  userId: z.string().uuid().optional(),
  type: AlertTypeSchema.optional(),
  severity: AlertSeveritySchema.optional(),
  status: AlertStatusSchema.optional(),
  minRiskScore: z.number().min(0).max(100).optional(),
  startDate: z.string().datetime().optional(),
  endDate: z.string().datetime().optional(),
});

export type AlertFilter = z.infer<typeof AlertFilterSchema>;

export const AlertSummarySchema = z.object({
  total: z.number().int().min(0),
  bySeverity: z.object({
    critical: z.number().int().min(0),
    high: z.number().int().min(0),
    medium: z.number().int().min(0),
    low: z.number().int().min(0),
  }),
  byStatus: z.object({
    active: z.number().int().min(0),
    investigating: z.number().int().min(0),
    dismissed: z.number().int().min(0),
    resolved: z.number().int().min(0),
    escalated: z.number().int().min(0),
  }),
  avgRiskScore: z.number().min(0).max(100),
});

export type AlertSummary = z.infer<typeof AlertSummarySchema>;
